from .page import *
from .list_records import *
from .crud_list_records import *
from .form import *
from .edit import *
from .view import *
from .create import *
from .delete import *
from .notifications import *